---
- hosts: prod_sclbuilder_db
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: "Install packages"
      dnf: "name={{ item }} state=present"
      with_items:
        - git
        - nginx
        

  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: https://github.com/miracle-as/sclbuilder-ui.git
        dest: /opt/sclbuilder-ui

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted

