---
- hosts: prod_sclbuilder_database

  vars_files:
    - vars.yml

  tasks:
#    - name: "Find out if PostgreSQL is initialized"
#      ansible.builtin.stat:
#        path: "/var/lib/pgsql/data/pg_hba.conf"
#      register: postgres_data

#    - name: "Initialize PostgreSQL"
#      shell: "initdb /var/lib/pgsql/data"
#      when: not postgres_data.stat.exists
 
#    - name: "Start and enable services"
#      service: "name={{ item }} state=started enabled=yes"
#      with_items:
#        - postgresql
 
    - name: "Create app database"
      postgresql_db:
        state: present
        name: "{{ db_name }}"

    - name: "Create db user"
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"

    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: no
        privs: all

#    - name: "Allow md5 connection for the db user"
#      postgresql_pg_hba:
#        dest: "~/data/pg_hba.conf"
#        contype: host
#        databases: all
#        method: md5
#        users: "{{ db_user }}"
#        create: true
#      become: yes
#      become_user: postgres
#      notify: restart postgres


#  handlers:
#    - name: restart postgres
#      service: name=postgresql state=restarted
