---
- hosts: prod_sclbuilder_db
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: "Install packages"
      dnf: "name={{ item }} state=present"
      with_items:
        - git
        - nginx
        - uwsgi

  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: "https://github.com/miracle-as/{{ repository }}.git"
        dest: /opt/{{ repository }}

  handlers:
    - name: restart uwsgi
      service: name=uwsgi state=restarted

