---
- hosts: prod_sclbuilder_db

  vars_files:
    - vars.yml

  pre_tasks:
    - name: "Install packages"
      dnf: "name={{ item }} state=present"
      with_items:
        - git
        - nginx

  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: "https://github.com/miracle-as/{{ repository }}.git"
        dest: "/opt/{{ repository }}"

    - name: Install pip requirements
      pip:
        requirements: "/opt/{{ repository }}/requirements.txt"
        virtualenv: "/opt/{{ repository }}/venv"
        virtualenv_command: /usr/bin/python3.6 -m venv

  handlers:
    - name: restart uwsgi
      service: name=uwsgi state=restarted

