---
- hosts: prod_sclbuilder_db
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: "Install packages"
      dnf: "name={{ item }} state=present"
      with_items:
        - git
        - nginx
        - uwsgi

  tasks:
    - name: Git checkout
      ansible.builtin.git:
        repo: "https://github.com/miracle-as/{{ repository }}.git"
        dest: "/opt/{{ repository }}"

    - pip: install requirements
      requirements: "/opt/{{ repositoty }}/requirements.txt"
      virtualenv: "/opt/{{ repository }}/venv"
      virtualenv_command: /usr/bin/python3.6 -m venv

  handlers:
    - name: restart uwsgi
      service: name=uwsgi state=restarted

