- name: Download pypi packages
  hosts: prod_sclbuilder_worker
  vars_files:
    - vars.yml
  tasks:
  - name: Install rhel
    ansible.builtin.package:
      name:
        - redis
        - python38-pip
        - python38-devel
        - wget
        - rpm-build
        - scl-utils-build
        - scl-utils
        - help2man
        - unzip
        - openssl-devel
        - libtool-ltdl-devel
        - sphinx
        - python38-wheel
        - make
        - gcc
        - libffi-devel
        - openldap-devel
        - libxml2-devel
        - xmlsec1
        - xmlsec1-openssl
        - libpq-devel
        - platform-python-devel
      state: present

  - name: Install bottle python package
    pip:
      name:
        - requirements-parser
        - spec2scl
        - setuptools_rust
      executable: pip-3.8

  - name: Copy the downloader script
    ansible.builtin.template:
      src: sclbuilder_download.sh.j2
      dest: /usr/local/bin/sclbuilder_download.sh
      owner: root
      group: root
      mode: '0755'

  - name: Copy the downloader python script
    ansible.builtin.template:
      src: pip-downloader.py.j2
      dest: /usr/local/bin/pip-downloader.py
      owner: root
      group: root
      mode: '0755'

  - name: Copy the downloar create original spec name
    ansible.builtin.template:
      src:  sclbuilder_create_original_specfile.sh.j2
      dest: /usr/local/bin/sclbuilder_create_original_specfile.sh
      owner: root
      group: root
      mode: '0755'

  - name: Copy the downloader env script
    ansible.builtin.template:
      src:  setbuildenv.sh.j2
      dest: /usr/local/bin/setbuildenv.sh
      owner: root
      group: root
      mode: '0755'
  

  - name: Copy the rpmbuilder script
    ansible.builtin.template:
      src: mergefiles.sh.j2
      dest: /usr/local/bin/mergefiles.sh
      owner: root
      group: root
      mode: '0755'

  - name: Copy the rpmbuilder script
    ansible.builtin.template:
      src: sclbuilder_buildscl.sh.j2
      dest: /usr/local/bin/sclbuilder_buildscl.sh
      owner: root
      group: root
      mode: '0755'

  - name: Copy the mandatory after setup addon
    ansible.builtin.template:
      src:   mandatory_after_setup.add.j2
      dest: /usr/local/bin/mandatory_after_setup.add
      owner: root
      group: root
      mode: '0755'

  - name: Copy the mandatory after setup script
    ansible.builtin.template:
      src:   mandatory_after_setup.sh.j2
      dest: /usr/local/bin/mandatory_after_setup.sh
      owner: root
      group: root
      mode: '0755'
