---
- name: "Create a temporary rhel builder"
  hosts: localhost
  connection: local
  tasks:
  - name: "vagrant start a rhel8 builder"
    shell: "vagrant up"
  - name: "save old ssh config file"
    shell: "vagrant ssh-config >  builder.conf"
  - name: "copy key to servers"
    shell: "vagrant scp ~/.ssh/scldistro scldistro"

- name: Build openstack components
  hosts: builders
  tasks:
     - name: Build the scl
       vars:
          - version: "glance-stable-train"
          - branch:  "stable/train"
          - project:  "glance"
          - organisation: "met"
          - scl_version: "train"
          - scl_release: "1"
          - scl_description: "A precompiled package which installed the requirements for running the service"
          - repo_url: "https://github.com/openstack/glance.git"
          - requirementfile: /usr/local/etc/awx.requirements.txt
       include_role:
         name:  miracle-ansible-role-pipfreeze2scl 
  become: True
