---

- name: Initial database seed
  hosts: sclbuilder
  tasks:
  - name: Simple select query to acme db
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: SELECT version()
    become: yes
    become_user: sclbuilder

  - name: Insert project
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: INSERT INTO projects_project (slug, projectname,  projectversion,  projectdescription,  projectstatus,  projecturl,  projectcreated) VALUES( '{{ project.slug }}', '{{ project.name }}',  '{{ project.version }}',  '{{ project.description }}',  'Initial',  '{{ project.url }}',  '{{ ansible_date_time.date }} ') ON CONFLICT (projectname) DO NOTHING;
    become: yes
    become_user: sclbuilder
    loop:
      - { "slug": "awxrpm", "name": "Miracle Ansible", "version": "1.0.0", "description": "Miracle supported ansible related opensoure projects", "url": "miracle.dk" }
    loop_control:
      loop_var: project


  - name: Insert subproject
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: INSERT INTO projects_subproject (slug, projectname_id, subprojectname, subprojectversion,  subprojectdescription,  subprojectstatus,  subprojecturl,  subprojectcreated) VALUES( '{{ subproject.slug }}', '{{ subproject.projectname }}', '{{ subproject.name }}',  '{{ subproject.version }}',  '{{ subproject.description }}',  'Initial',  '{{ subproject.url }}',  '{{ ansible_date_time.date }} ') ON CONFLICT (subprojectname) DO NOTHING;
    become: yes
    become_user: sclbuilder
    loop:
      - { "slug": "awxrpm", "projectname": "Miracle Ansible", "name": "AWX-RPM", "version": "1.0.0", "description": "Miracle supported ansible related opensoure projects", "url": "miracle.dk" }
    loop_control:
      loop_var: subproject
#NSERT INTO projects_subproject (projectname_id,  subprojectname,  subprojectversion,  subprojectdescription,  subprojectstatus,  subprojecturl,  subprojectcreated) VALUES('Miracle ansible',  'awx-rpm',  '1.0.0',  'Miracle supported ansible awx',  'Initial',  'http://awx.wiki',  '2021-12-01 08:21:32.861950') RETURNING 'projects_subproject_id' ;



  - name: Insert subproject
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: INSERT INTO projects_subproject (slug, subprojectname_id, releasename, releaseversion, releasebuild, releasedescription,  releasestatus,  subprojectcreated) VALUES( '{{ release.slug }}', '{{ release.subprojectname }}', '{{ release.name }}',  '{{ release.version }}', '{{ release.build }}', '{{ release.description }}',  'Initial',  '{{ ansible_date_time.date }} ') ON CONFLICT (releasename) DO NOTHING;
    become: yes
    become_user: sclbuilder
    loop:
      - { "slug": "awxrpm", "subprojectname": "AWX-RPM", "name": "19.5.0", "version": "19.5.1", "build": "001", "description": "Miracle supported RPM/SCL based AWX ", "url": "awx-rpm.wiki" }
    loop_control:
      loop_var: release
#INSERT INTO projects_subprojectrelease (subprojectname_id,  releasename,  releaseversion,  releasebuild,  releasedescription,  releasestatus,  releasecreated) VALUES('awx-rpm',  '19.5.0',  '19.5.0',  '001',  'Autocreated from repo',  'Initial',  '2021-12-01 08:28:11.240412') RETURNING 'projects_subprojectrelease_id' ;






