---

- name: Initial database seed
  hosts: sclbuilder
  tasks:
  - name: Simple select query to acme db
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: SELECT version()
    become: yes
    become_user: sclbuilder

