---

- name: Initial database seed
  hosts: prod_sclbuilder_worker
  tasks:

  - name: Install
    ansible.builtin.package:
      name: 
        - python38-psycopg2
        - python38-pip
        - python38-devel
      state: present

  - name: Correct python3
    community.general.alternatives:
      name: python3
      path: /usr/bin/python3.8


    
    