---

- name: Initial database seed
  hosts: prod_sclbuilder_sclbuilder
  vars_files:
    - vars.yml
  tasks:
  - name: create_specfiles | Touch /root/rpmbuild/SOURCES/LICENSE
    shell: touch /root/rpmbuild/SOURCES/LICENSE

  - name: create_specfiles | run the builder script
    shell: /usr/local/bin/create.sclspec.sh
  
