---

- name: Setup a project in sclbuilder
  hosts: sclbuilder
  vars:
    organisation: "miracle"
    project: "awxrpm"
    version: "1.0.0"
    description: "Miracle supported awx installed with software collections"

  tasks:
  - name: Check if it already exists
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: select * from  projects_project where projectname = '{{ project }}';
    register: project 
    become: yes
    become_user: sclbuilder
  
  - name: insert when missing
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: >-
        inset into projecs_project set 
        projectname, projectversion, projectstatus, projectdescription, projectstatus, projectcreated 
        VALUES (
        '{{ project }}',
        '{{ version }}',
        'Initial',
        '{{ description }}',
        NOW(),

        )
    register: insertproject
    become: yes
    become_user: sclbuilder
