---

- name: Initial database seed
  hosts: sclbuilder
  tasks:
  - name: Simple select query to acme db
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: SELECT version()
    become: yes
    become_user: sclbuilder

  - name: Insert package
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: INSERT INTO projects_packages (slug, packageident, packagename, packageversion, packagestatus,  packagecreated) VALUES( '{{ package.slug }}', '{{ package.name }}',  '{{ package.version }}' 'Initial',  '{{ ansible_date_time.date }} ') ON CONFLICT (slug) DO NOTHING;
    become: yes
    become_user: sclbuilder
#INSERT INTO projects_subprojectrelease (subprojectname_id,  releasename,  releaseversion,  releasebuild,  releasedescription,  releasestatus,  releasecreated) VALUES('awx-rpm',  '19.5.0',  '19.5.0',  '001',  'Autocreated from repo',  'Initial',  '2021-12-01 08:28:11.240412') RETURNING 'projects_subprojectrelease_id' ;




