---
- name: Initial database seed
  hosts: prod_awx
  vars:
    - organisation: "miracle"
    - myrepo: "https://github.com/ansible/awx.git"
    - project: "awxrpm"
    - version: "19.4.0"
  tasks:

  - name: Install rhel
    ansible.builtin.package:
      name: 
        - redis
        - python38-pip
        - python38-devel
        - python3-devel
        - python3-requests
        - python38-requests
        - wget
        - rpm-build
        - scl-utils-build
        - scl-utils
        - help2man
        - unzip
        - openssl-devel
        - libtool-ltdl-devel
        - python3-sphinx
        - make
        - gcc
        - libffi-devel
        - openldap-devel
        - libxml2-devel
        - xmlsec1-devel 
        - xmlsec1-openssl-devel
        - libpq-devel
        - platform-python-devel
      state: present

  - name: Install bottle python package
    pip:
      name: 
        - requests
        - requirements-parser
        - spec2scl
        - setuptools_rust
        - wheel
        
  - name: Install psyorg in the platforn python
    command: /usr/libexec/platform-python -m pip install psycopg2-binary 
    become: True

  - name: Add the user 'sclbuilder'
    ansible.builtin.user:
      name: sclbuilder
      comment: service account for scl create
    become: True

  - name: Simple select query to acme db
    postgresql_query:
      db: sclbuilder
      login_host: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: SELECT version()
    become: yes
    become_user: sclbuilder

  - name: Creates directory
    file:
      path: /root/checkout
      state: absent

  - name: Git checkout
    ansible.builtin.git:
      repo: "{{  myrepo  }}"
      dest: /root/checkout/
      clone: yes
   


