---

- name: Initial database seed
  hosts: prod_sclbuilder_worker
  tasks:
  - name: Simple select query to prod_sclbuilder_worker db
    postgresql_query:
      db: prod_sclbuilder_worker
      login_user: "prod_sclbuilder_worker"
      login_password: "django2know"
      query: SELECT version()
    become: yes
    become_user: prod_sclbuilder_worker

  - name: Insert package
    postgresql_query:
      db: prod_sclbuilder_worker
      login_user: "prod_sclbuilder_worker"
      login_password: "django2know"
      query: >-
        INSERT INTO projects_package 
        (
          slug,
          packagename,
          packageversion, 
          packagestatus,  
          packagecreated
        ) 
        VALUES
        ( 
          '{{ slug }}',
          '{{ name }}',
          '{{ version }}',
          'Initial',
          '{{ ansible_date_time.date }} '
        )
        ON CONFLICT (slug) DO NOTHING;
    become: yes
    become_user: prod_sclbuilder_worker


