---

- name: Initial database seed
  hosts: prod_sclbuilder_worker
  tasks:
  - name: Simple select query to acme db
    postgresql_query:
      db: prod_sclbuilder_worker
      login_user: "prod_sclbuilder_worker"
      login_password: "django2know"
      query: SELECT version()
    become: yes
    become_user: prod_sclbuilder_worker

  - name: Insert package
    postgresql_query:
      db: prod_sclbuilder_worker
      login_user: "prod_sclbuilder_worker"
      login_password: "django2know"
      query: select * from  projects_package where packagestatus IS NULL;
    register: result
    become: yes
    become_user: prod_sclbuilder_worker
  
#  - debug: 
#      var: result.query_all_results.0

#  - name: loop packages
#    debug: msg="HERWEGO :{{ item.id }}"
#    with_items:
#    - "{{ result.query_all_results.0 }}"

  - name: Copy the rpmbuilder script
    ansible.builtin.template:
      src: prod_sclbuilder_worker_updaterelease.sh.j2
      dest: /usr/local/bin/prod_sclbuilder_worker_updaterelease.sh
      owner: root
      group: root 
      mode: '0755'
    become: yes

  - name: loop packages
    postgresql_query:
      db: prod_sclbuilder_worker
      login_user: "prod_sclbuilder_worker"
      login_password: "django2know"
      query: "update projects_package set packagestatusurl = 'http://repos.pip2scl.dk/logos/amberball.png' where id = {{ item.id }} ; " 
    register: result
    become: yes
    become_user: prod_sclbuilder_worker
    with_items:
    - "{{ building.query_all_results.0 }}"
  