---

- name: Initial database seed
  hosts: sclbuilder
  tasks:
  - name: Simple select query to acme db
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: SELECT version()
    become: yes
    become_user: sclbuilder

  - name: Insert package
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: select * from  projects_package where packagestatus IS NULL;
    register: result
    become: yes
    become_user: sclbuilder
  
#  - debug: 
#      var: result.query_all_results.0

#  - name: loop packages
#    debug: msg="HERWEGO :{{ item.id }}"
#    with_items:
#    - "{{ result.query_all_results.0 }}"

  - name: loop packages
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: "update projects_package set packagestatus = 'Initial' where id = {{ item.id }} ; " 
    register: result
    become: yes
    become_user: sclbuilder
    with_items:
    - "{{ result.query_all_results.0 }}"

  - name: Insert package
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: select * from  projects_package where packagestatus = 'Completed';
    register: completed
    become: yes
    become_user: sclbuilder

  - name: loop packages
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: "update projects_package set packagestatusurl = 'http://repos.pip2scl.dk/logos/greenball.png' where id = {{ item.id }} ; " 
    register: result
    become: yes
    become_user: sclbuilder
    with_items:
    - "{{ completed.query_all_results.0 }}"
  
  - name: Insert package
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: select * from  projects_package where packagestatus = 'Building';
    register: building
    become: yes
    become_user: sclbuilder


  - name: loop packages
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: "update projects_package set packagestatusurl = 'http://repos.pip2scl.dk/logos/amberball.png' where id = {{ item.id }} ; " 
    register: result
    become: yes
    become_user: sclbuilder
    with_items:
    - "{{ building.query_all_results.0 }}"
  