---

- name: Initial database seed
  hosts: sclbuilder
  tasks:
  - name: Simple select query to acme db
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: SELECT version()
    become: yes
    become_user: sclbuilder

  - name: Select the all packages where packagesourcefileurl is NULL
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: select * from  projects_package where packagesourcefileurl IS NULL;
    register: sourceurlmissingpackages
    become: yes
    become_user: sclbuilder

  - name: Set them to building
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: "update projects_package set packagesourcefilestatus = 'Building' , packagesourcefileurl = 'http://repos.pip2scl.dk/SOURCES/{{ item.packagename }}-{{ item.packageversion}}.tar.gz'  where id = {{ item.id }} ; " 
    register: adoptedpackages
    become: yes
    become_user: sclbuilder
    with_items:
    - "{{ sourceurlmissingpackages.query_all_results.0 }}"


  - name: Select the new ones 
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: select * from  projects_package where packagesourcefilestatus 	IS NULL;;
    register: newpackages
    become: yes
    become_user: sclbuilder
  
  - name: Set them to building
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: "update projects_package set packagesourcefilestatus = 'Building'  where id = {{ item.id }} ; " 
      #query: "update projects_package set packagesourcefilestatus = 'Building', packagesourcefileurl = 'http://repos.pip2scl.dk/SOURCES/{{ item.packagename }}-{{ item.packageversion}}.tar.gz'  where id = {{ item.id }} ; " 
    register: adoptedpackages
    become: yes
    become_user: sclbuilder
    with_items:
    - "{{ newpackages.query_all_results.0 }}"


  - name: Select the building candidates
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: select packagename, packageversion from  projects_package where packagesourcefilestatus == 'Building';
    register: result
    become: yes
    become_user: sclbuilder
  
  - name: Copy the downloader script
    ansible.builtin.template:
      src: sclbuilder_download.sh.j2
      dest: /usr/local/bin/sclbuilder_download.sh
      owner: root
      group: root 
      mode: '0755'
    become: yes

  - name: Copy the downloader python script
    ansible.builtin.template:
      src: pip-downloader.py.j2
      dest: /usr/local/bin/pip-downloader.py
      owner: root
      group: root 
      mode: '0755'
    become: yes

  - name: Copy the downloader env script
    ansible.builtin.template:
      src:  setbuildenv.sh.j2
      dest: /usr/local/bin/setbuildenv.sh
      owner: root
      group: root 
      mode: '0755'
    become: yes

  - name: Run download on our targets
    command: "/usr/local/bin/sclbuilder_download.sh {{ item.packagename }}=={{ item.packageversion }}"
    become: yes
    register: download
    with_items:
    - "{{ result.query_all_results.0 }}"

  - name: Run download on our targets
    uri:
      url: "http://repos.pip2scl.dk/SOURCES/{{ item.packagename }}-{{ item.packageversion }}.tar.gz"
    register: urlcheck
    with_items:
    - "{{ result.query_all_results.0 }}"

  - debug: 
      var: urlcheck


  - name: update database if based on curl
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_password: "django2know"
      query: "update projects_package set packagesourcefilestatus = 'Completed' where id = {{ item.id }} ; " 
    register: result
    with_items:
      - "{{ urlcheck.results }}"
    when:  item.status == 200

