- name: Initial database seed
  hosts: prod_sclbuilder_database
  gather_facts: False
  tasks:
  - name: Simple select query to acme db
    postgresql_query:
      db: sclbuilder
      login_host: localhost
      login_user: "sclbuilder"
      login_password: "django2know"
      query: SELECT version()

  - name: Insert package
    postgresql_query:
      db: sclbuilder
      login_host: localhost
      login_user: "sclbuilder"
      login_password: "django2know"
      query: select * from  projects_package where packagestatus IS NULL;
    register: result
  
  - name: loop packages
    postgresql_query:
      db: sclbuilder
      login_host: locahost
      login_user: "sclbuilder"
      login_password: "django2know"
      query: "update projects_package set packagestatus = 'Initial' where id = {{ item.id }} ; " 
    register: result
    with_items:
    - "{{ result.query_all_results.0 }}"

  - name: get all packages
    postgresql_query:
      db: sclbuilder
      login_host: localhost
      login_user: "sclbuilder"
      login_password: "django2know"
      query: select * from  projects_package;
    register: allpackages

  - name: set expected urls
    postgresql_query:
      db: sclbuilder
      login_host: localhost
      login_user: "sclbuilder"
      login_password: "django2know"
      query: >-
        update projects_package set 
        packagestatus = 'Building',
        packagerpmfilesurl = 'http://repos.pip2scl.dk/META/{{ item.packagename }}-{{ item.packageversion }}.rpmfiles',
        packagestatusurl = 'http://repos.pip2scl.dk/logos/amberball.png', 
        packagesourcefileurl = 'http://repos.pip2scl.dk/SOURCES/{{ item.packagename }}-{{ item.packageversion }}.tar.gz', 
        packageorgspecfileurl = 'http://repos.pip2scl.dk/SPECS/{{ item.packagename }}-{{ item.packageversion }}.original.spec', 
        packagespecfileurl = 'http://repos.pip2scl.dk/SPECS/{{ item.packagename }}-{{ item.packageversion }}.verified.spec', 
        packagesclfileurl = 'http://repos.pip2scl.dk/SPECS/{{ item.packagename }}-{{ item.packageversion }}.scl', 
        Packagesclrpmfilesurl = 'http://repos.pip2scl.dk/META/{{ item.packagename }}-{{ item.packageversion }}.sclfiles',
        packagetweakscript = 'http://repos.pip2scl.dk/TWEAKS/{{ item.packagename }}-{{ item.packageversion }}.tweak' 
        where id = {{ item.id }} ; 
    with_items:
    - "{{ allpackages.query_all_results.0 }}"


  - name: get all packages  where packagerpmfilestatus is null
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_host: localhost
      login_password: "django2know"
      query: select id, packagestatus,  packagesclrpmfilestatus from  projects_package where packagesclfilestatus IS NULL ;
    register: sclpackages

  - name: set expected urls
    postgresql_query:
      db: sclbuilder
      login_host: localhost
      login_user: "sclbuilder"
      login_password: "django2know"
      query: >-
        update projects_package set 
        packagestatus = 'Building',
        packagesclrpmfilestatus = 'Building'
        where id = {{ item.id }} ; 
    with_items:
    - "{{ sclpackages.query_all_results.0 }}"


  - name: get all packages  where packagerpmfilestatus is null
    postgresql_query:
      db: sclbuilder
      login_host: localhost
      login_user: "sclbuilder"
      login_password: "django2know"
      query: select id, packagestatus, packagesclrpmfilestatus from  projects_package where packagesclrpmfilestatus IS NULL ;
    register: sclrpmpackages

  - name: set expected sclrpmpackages
    postgresql_query:
      db: sclbuilder
      login_host: localhost
      login_user: "sclbuilder"
      login_password: "django2know"
      query: >-
        update projects_package set 
        packagestatus = 'Building',
        packagesclrpmfilestatus = 'Building'
        where id = {{ item.id }} ; 
    with_items:
    - "{{ sclrpmpackages.query_all_results.0 }}"


  - name: get all packages  where packagerpmfilestatus is null
    postgresql_query:
      db: sclbuilder
      login_host: localhost
      login_user: "sclbuilder"
      login_password: "django2know"
      query: select id, packagestatus, packagerpmfilestatus from  projects_package where packagerpmfilestatus IS NULL ;
    register: rpmpackages

  - name: set expected urls
    postgresql_query:
      db: sclbuilder
      login_user: "sclbuilder"
      login_host: localhost
      login_password: "django2know"
      query: >-
        update projects_package set 
        packagestatus = 'Building',
        packagerpmfilestatus = 'Building'
        where id = {{ item.id }} ; 
    with_items:
    - "{{ rpmpackages.query_all_results.0 }}"


  - name: Insert package
    postgresql_query:
      db: sclbuilder
      login_host: localhost
      login_user: "sclbuilder"
      login_password: "django2know"
      query: select * from  projects_package where packagestatus = 'Completed';
    register: completed

  - name: loop packages
    postgresql_query:
      db: sclbuilder
      login_host: localhost
      login_user: "sclbuilder"
      login_password: "django2know"
      query: "update projects_package set packagestatusurl = 'http://rpm.miracle.dk/logos/greenball.png' where id = {{ item.id }} ; " 
    register: result
    with_items:
    - "{{ completed.query_all_results.0 }}"
  
  - name: Insert package
    postgresql_query:
      db: sclbuilder
      login_host: localhost
      login_user: "sclbuilder"
      login_password: "django2know"
      query: select * from  projects_package where packagestatus = 'Building';
    register: building

  - name: set package status based on substati
    postgresql_query:
      db: sclbuilder
      login_host: lolcahost
      login_user: "sclbuilder"
      login_password: "django2know"
      query: >- 
        update projects_package 
        set packagestatus = 'Completed' 
        where (
        packagesourcefilestatus = 'Completed' AND 
        packageorgspecfilestatus = 'Completed' AND  
        packagespecfilestatus = 'Completed' AND  
        packagerpmfilestatus = 'Completed' AND 
        packagesclrpmfilestatus = 'Completed' )
    register: statusresult
    with_items:
    - "{{ building.query_all_results.0 }}"
   
