---
- name: Build openstack components
  hosts: sclbuilder
  tasks:
    - name: Build the scl
      vars:
         - name: "awx-rpm"
         - version: "awxrpm"
         - project:  "awx"
         - organisation: "miracle"
         - scl_version: "19.4.0"
         - awx_image_version: "19.4.0"
         - scl_release: "1"
         - scl_description: "A precompiled package which installed the requirements for running the service"
         - requirementfile: "http://repos.pip2scl.dk/awx.requirements.txt"
         - dependencyfile: "http://repos.pip2scl.dk/DEPENDENCIES/awx-19.4.0.dep"
         - project_dir: "/opt/{{ organisation }}/{{ name }}"
         - repo_url: "https://github.com/ansible/awx.git"
         - branch: "19.4.0"
      include_role:
         name:  miracle-ansible-role-awxprebuild
  become: True

