---
- name: "Create a temporary rhel builder"
  hosts: localhost
  connection: local
  tasks:
  - name: "vagrant start a rhel8 builder"
    shell: "vagrant up"
  - name: "save old ssh config file"
    shell: "vagrant ssh-config >  builder.conf"
  - name: "copy key to servers"
    shell: "vagrant scp ~/.ssh/scldistro scldistro"

- name: install openstack components
  hosts: api
  tasks:
     - name: install
       vars:
          - version: "stable-train"
          - project:  "keystone"
          - organisation: "met"
          - scl_version: "train"
          - scl_release: "1"
       include_role:
         name:  miracle-ansible-role-install-openstack-component
  become: True
