---
- name: "Create a temporary rhel builder"
  hosts: localhost
  connection: local
  tasks:
  - name: "vagrant start a rhel8 builder"
    shell: "vagrant up"
  - name: "save old ssh config file"
    shell: "vagrant ssh-config >  builder.conf"
  - name: "copy key to servers"
    shell: "vagrant scp ~/.ssh/scldistro scldistro"

- name: Build openstack components
  hosts: builders
  tasks:
     - name: Build the scl
       vars:
          - version: "keystone-stable-train"
          - branch:  "stable/train"
          - project:  "keystone"
          - organisation: "met"
          - scl_version: "train"
          - scl_release: "1"
          - scl_description: "A precompiled package which installed the requirements for running the service"
          - repo_url: "https://github.com/openstack/keystone.git"
       include_role:
         name:  miracle-ansible-role-pipfreeze2scl 
  become: True

  #- name: Build openstack components
  #hosts: targets
  #tasks:
  #   - name: Build the rpms
  #     vars:
  #        - version: "keystone-stable-train"
  #        - branch:  "stable/train"
  #        - project:  "keystone"
  #        - organisation: "met"
  #        - scl_version: "train"
  #        - scl_release: "1"
  #        - scl_description: "A precompiled package which installed the requirements for running the service"
  #        - repo_url: "https://github.com/openstack/keystone.git"
  #     include_role:
  #       name:  miracle-ansible-role-build-scl-rpms
  #become: True

  #- name: "Destroy a temporary rhel builder"
  #hosts: localhost
  #connection: local
  #tasks:
  #- name: "vagrant kill the rhel8 builder"
  #  shell: "vagrant destroy -f"
