- name: Build openstack components
  hosts: repos
  tasks:
     - name: setup repos
       vars:
          - version: "1.0.0"
          - url: "repos.pip2scl.dk"
       include_role:
         name:  miracle-ansible-role-reposerver
  become: True
